CREATE TABLE cake (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR UNIQUE NOT NULL,
    image_url VARCHAR NOT NULL
);

INSERT INTO cake (name, image_url)
VALUES
    ('Birthday Chocolate Truffle Cake', 'https://www.getatoz.com/images/birthday-chocolate-truffle-cake-name.png'),
    ('Birthday Dark Chocolate Cake', 'https://www.getatoz.com/images/birthday-dark-chocolate-cake-name.png'),
    ('Birthday Black Forest Cake', 'https://www.getatoz.com/images/birthday-black-forest-cake-name.png'),
    ('Birthday Almond White Forest Cake', 'https://www.getatoz.com/images/birthday-almond-white-forest-cake-name.png');

CREATE TABLE yum_factor (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number INT UNIQUE NOT NULL
);

INSERT INTO yum_factor (number)
VALUES (1), (2), (3), (4), (5);

CREATE TABLE review (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cake_id SMALLINT REFERENCES cake(id) ON DELETE CASCADE,
    comment VARCHAR(200) NOT NULL,
    yum_factor_id SMALLINT REFERENCES yum_factor(id)
);

INSERT INTO review (cake_id, comment, yum_factor_id)
VALUES ((SELECT id FROM cake WHERE name = 'Birthday Chocolate Truffle Cake'), 'Brilliant Almond White Forest Cake', (SELECT id FROM yum_factor WHERE number = 4)),
        ((SELECT id FROM cake WHERE name = 'Birthday Dark Chocolate Cake'), 'Superb Dark Chocolate Cake', (SELECT id FROM yum_factor WHERE number = 5)),
        ((SELECT id FROM cake WHERE name = 'Birthday Black Forest Cake'), 'Classic Dark Chocolate Cake', (SELECT id FROM yum_factor WHERE number = 5)),
        ((SELECT id FROM cake WHERE name = 'Birthday Almond White Forest Cake'), 'Tasty Almond White Forest Cake', (SELECT id FROM yum_factor WHERE number = 4));

